# 基于官方apache/kafka:3.9.0镜像（内置KRaft支持）
# FROM apache/kafka:3.9.0F
FROM docker.m.daocloud.io/apache/kafka:3.9.0

# 维护者信息（可选）
LABEL maintainer="madison"

# 核心环境变量（固化KRaft单节点配置，开发测试用）
ENV KAFKA_HOME=/opt/kafka \
    PATH=$PATH:/opt/kafka/bin \
    TZ=Asia/Shanghai \
    LANG=C.UTF-8 \
    KAFKA_NODE_ID=1 \
    # 固定集群ID，开发测试无需随机
    CLUSTER_ID=kafka-cluster-1234 \
    KAFKA_PROCESS_ROLES=broker,controller \
    KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
    KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
    KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
    # 注意：替换为你的宿主机IP（或localhost，仅本机访问）
    KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
    KAFKA_CONTROLLER_QUORUM_VOTERS=1@host.docker.internal:9093

# 初始化存储目录
RUN mkdir -p /var/lib/kafka/data && \
    ${KAFKA_HOME}/bin/kafka-storage.sh format -t $CLUSTER_ID -c ${KAFKA_HOME}/config/kraft/server.properties

# 暴露端口（broker+controller）
EXPOSE 9092 9093

# 启动命令（复用官方镜像的启动脚本，自动加载环境变量） ${KAFKA_HOME}
CMD ["kafka-server-start.sh", "/opt/kafka/config/kraft/server.properties"]